### ISSUE TITLE
Add support for soy aka closure-templates

### ISSUE THREAD

**Issue by lpellegr** [GoogleCloudPlatform/google-cloud-graalvm-support#119]
https://github.com/google/closure-templates

for instance when used with Micronaut:

https://micronaut-projects.github.io/micronaut-views/latest/guide/#soy

**Comment by dzou** [comment]
Thanks for the request, we will look into supporting this.

**Comment by dzou** [comment]
Hey sorry for the delay on this. We've been spending time investigating how to test and validate the GCP libraries recently and have not been expanding the scope of our supported libraries.

Unfortunately we decided that we are not planning on supporting this library because it is outside the scope of Google Cloud; our project currently is just targeting client libraries for GCP services (like Pub/Sub, Spanner, Storage, etc.). Not quite ready to extend to all google projects.

Apologies as this should be been communicated earlier. Will close this for now. If you need some assistance on figuring out the reflection configuration for this library I will be happy to give some pointers.
