### ISSUE TITLE
The compatibility table to include GraalVM versions

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/google-cloud-graalvm-support#181]
It seems that GraalVM introduces backward-incompatible changes. How about the compatibility table (https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support#client-library-versions) including GraalVM versions to clarify GraalVM versions we used for google-cloud-graalvm-support releases?

@dzou What do you think?

**Comment by dzou** [comment]
Yeah! Will do. I have some changes prepared in this PR which introduces this graalvm version table: https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support/pull/165/files

Still waiting for it to be unblocked since we think there is a bug in the 21.2.0 version, but I might just have to ignore a sample test temporarily and get it committed.

**Comment by dzou** [comment]
Thanks for the suggestion again. I just added this in; please see: https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support#client-library-versions

**Comment by suztomo** [comment]
Nice. Thank you.
